login/urls.py
from django.contrib import admin
from django.urls import path
from task import views
from django.urls import path, include
from django.contrib.auth import views as auth_views
from usuarios import views as usuarios_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('signup/', views.signup, name='signup'),
    path('home/', views.home, name='home'),
    path('', views.home, name='home'),  # O quita esta si ya usas 'home/'
    path('revista/', include('revista.urls')),  # <- con prefijo
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('perfil/', views.perfil_usuario, name='perfil'),
    path('editar_perfil/', usuarios_views.editar_perfil, name='editar_perfil'),
    path('usuarios/', include('usuarios.urls')),
    path('task/', include('task.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/urls.py
# task/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('enviar_articulo/', views.enviar_articulo, name='enviar_articulo'),
    # Otras URLs específicas de la aplicación 'task'
]

task/models.py
from django.db import models
from django.contrib.auth.models import User

class Articulo(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=255)
    resumen = models.TextField()
    archivo = models.FileField(upload_to='articulos/')  # Guarda los archivos en la carpeta 'articulos/'
    fecha_envio = models.DateTimeField(auto_now_add=True)
    # Puedes agregar más campos como 'palabras_clave', 'area_tematica', etc.

    def __str__(self):
        return self.titulo

task/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(label="Nombre", required=True)
    last_name = forms.CharField(label="Apellidos", required=True)
    email = forms.EmailField(label="Correo electrónico", required=True)

    class Meta:
        model = User
        fields = [
            "first_name", 
            "last_name", 
            "email", 
            "username", 
            "password1", 
            "password2"
        ]
    def clean_password2(self):
        password = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password is not None and password != password2:
            raise ValidationError("Las contraseñas no coinciden")
        return password2

    def clean_password1(self):
        password = self.cleaned_data.get("password1")
        if len(password) < 8:
            raise ValidationError("La contraseña debe tener al menos 8 caracteres")
        if not any(char.isdigit() for char in password):
            raise ValidationError("La contraseña debe contener al menos un número")
        if not any(char.isalpha() for char in password):
            raise ValidationError("La contraseña debe contener al menos una letra")
        # Puedes agregar más validaciones aquí:
        # if not any(char.isupper() for char in password):
        #     raise ValidationError("La contraseña debe contener al menos una mayúscula")
        # if not any(char.islower() for char in password):
        #     raise ValidationError("La contraseña debe contener al menos una minúscula")
        # if not any(char in "!@#$%^&*()_+=-`~[]\{}|;':\",./<>?" for char in password):
        #     raise ValidationError("La contraseña debe contener al menos un símbolo")
        return password
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("Este correo electrónico ya está registrado")
        return email
    
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exists():
            raise ValidationError("Este nombre de usuario ya existe")
        return username


    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        user.email = self.cleaned_data["email"]
        # afiliacion y pais no se guardan aquí porque no existen en el modelo User
        if commit:
            user.save()
        return user

task/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.db import IntegrityError
from .forms import CustomUserCreationForm
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from .articulo_forms import EnviarArticuloForm
from django.contrib import messages
from django.contrib.auth import logout, login


def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html', {
            'form': CustomUserCreationForm()
        })

    elif request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            try:
                user=form.save()
                login(request, user)  # Inicia sesión al usuario recién registrado
                return redirect('home')
            except IntegrityError:
                return render(request, 'signup.html', {
                    'form': form,
                    'error': 'Este usuario ya existe'
                })
        else:
            return render(request, 'signup.html', {
                'form': form
            })

def home(request):
    user = request.user  # Obtiene el usuario autenticado
    context = {'user': user}  # Crea el contexto para el template
    return render(request, 'home.html')

def logout_view(request):
    logout(request)
    return redirect('login')

@login_required
def perfil_usuario(request):
    print(f"Usuario autenticado: {request.user.is_authenticated}")
    print(f"Tipo de request.user: {type(request.user)}")
    return render(request, 'perfil.html', {
        'usuario': request.user
})
@login_required
def enviar_articulo(request):
    if request.method == 'POST':
        form = EnviarArticuloForm(request.POST, request.FILES)
        if form.is_valid():
            articulo = form.save(commit=False)
            articulo.autor = request.user
            articulo.save()
            messages.success(request, 'Tu artículo ha sido enviado exitosamente.')
            return redirect('enviar_articulo') # Redirige a la misma página con mensaje
        else:
            messages.error(request, 'Hubo un error al enviar el artículo. Por favor, revisa el formulario.')
    else:
        form = EnviarArticuloForm()
    return render(request, 'task/enviar_articulo.html', {'form': form})

task/templates/home.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <title>Entropy</title>
</head>

<body>

    <!-- Barra de navegación con tus vistas -->
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}"><i class="fas fa-home"></i> Inicio</a></li>
                <li>
                <li>
                    <a href="#">
                        <i class="fas fa-search"></i>
                    </a>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <div class="dropdown">
                        <button class="dropbtn">{{ user.username }} <i class="fas fa-chevron-down"></i></button>
                        <div class="dropdown-content">
                            <a href="{% url 'perfil_usuario' %}">Mi Perfil</a>
                            <form method="post" action="{% url 'logout' %}">
                                {% csrf_token %}
                                <button type="submit">Logout</button>
                            </form>
                        </div>
                    </div>
                </li>
                {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="{% url 'signup' %}">Register</a></li>
                {% endif %}
                <li><a href="{% url 'sobre_nosotros' %}">Sobre Nosotros</a></li>
                <li><a href="{% url 'archivos' %}">Archivos</a></li>
                <li><a href="{% url 'contacto' %}">Contacto</a></li>
                <li><a href="{% url 'equipo_editorial' %}">Equipo Editorial</a></li>
                <li><a href="{% url 'politicas' %}">Políticas</a></li>
                <li><a href="{% url 'enviar_articulo' %}">Enviar Artículo</a></li>
            </ul>
        </nav>
    </header>
    <!-- Contenido principal -->
    <main>
        <section>
            {% block content %}
            <h1>Entropy</h1>
            <p><em>Entropy</em> es una publicación científica de acceso abierto editada por la Universidad
                cooperativa de colombia...</p>

            <p>Sus artículos se publican en la plataforma
                (<a href="https://revistas.udistrital.edu.co/index.php/revcie">revistas.udistrital.edu.co</a>) y no
                tienen costo alguno...</p>
            <div class="propósito-alcance">

                <p>La Revista Científica de la Universidad Cooperativa de Colombia - Sede Neiva se establece como un
                    canal fundamental para la difusión de la producción científica de alta calidad generada por la
                    comunidad académica local, regional, nacional e internacional. Buscamos fomentar un diálogo abierto
                    y riguroso entre investigadores, académicos y profesionales de diversas disciplinas, contribuyendo
                    así al avance del conocimiento y a la solución de problemáticas relevantes para nuestro entorno.</p>

                <p>Si bien nuestra revista acoge investigaciones de diversas áreas del saber, actualmente ponemos un
                    énfasis especial en [Aquí podrías mencionar algunas áreas de interés prioritarias para la UCC Neiva,
                    si las conoces o si la universidad tiene fortalezas particulares. Por ejemplo: "ciencias sociales y
                    económicas", "ingenierías y tecnologías", "ciencias de la salud", "educación y humanidades"].
                    Invitamos a la comunidad científica a explorar nuestras convocatorias y a compartir sus valiosos
                    aportes.</p>

                <p>En la Revista Científica UCC Neiva, nos guiamos por principios fundamentales como la excelencia
                    académica, la ética en la investigación, la transparencia en el proceso editorial, el compromiso con
                    el acceso abierto al conocimiento y el fomento de la colaboración científica.</p>
            </div>


            <div class="detalles-revista">

                <p>L-ISSN: 0124-2253 - e-ISSN: 2344-8350</p>

            </div>

            <div class="llamada-accion">
                <p>¿Interesado en publicar?</p>
                <a href="{% url 'enviar_articulo' %}" class="boton-enviar">Enviar Artículo</a>
            </div>
            {% endblock %}
        </section>
    </main>

    <!-- Pie de página -->
    <footer>
        <div class="footer-container">
            <div class="footer-column universidad">
                <h3>Universidad Cooperativa de Colombia</h3>
                <p>Institución de Educación Superior sujeta a inspección y vigilancia por el Ministerio de Educación
                    Nacional.</p>
                <p><strong>Sede Principal:</strong> [Dirección de la Sede Principal]</p>
                <p><strong>NIT:</strong> [Número de Identificación Tributaria]</p>
                <div class="social-icons">
                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                    <a href="#"><i class="fab fa-youtube"></i></a>
                    {# Añade aquí los enlaces reales a las redes sociales de la universidad #}
                </div>
            </div>
            <div class="footer-column academicos">
                <h3>Académicos</h3>
                <ul>
                    <li><a href="#">Programas de Pregrado</a></li>
                    <li><a href="#">Programas de Posgrado</a></li>
                    <li><a href="#">Investigación</a></li>
                    <li><a href="#">Extensión y Proyección Social</a></li>
                    <li><a href="#">Biblioteca</a></li>
                    <li><a href="#">Educación Continua</a></li>
                </ul>
            </div>
            <div class="footer-column institucional">
                <h3>Institucional</h3>
                <ul>
                    <li><a href="{% url 'sobre_nosotros' %}">Sobre Nosotros</a></li>
                    <li><a href="#">Acreditación</a></li>
                    <li><a href="#">Transparencia</a></li>
                    <li><a href="#">Normatividad</a></li>
                    <li><a href="#">Sedes</a></li>
                    <li><a href="#">Trabaja con Nosotros</a></li>
                    <li><a href="#">Noticias y Eventos</a></li>
                </ul>
            </div>
            <div class="footer-column contacto">
                <h3>Contacto General</h3>
                <p><strong>Línea Gratuita Nacional:</strong> [Número de Línea Gratuita]</p>
                <p><strong>Teléfono Conmutador:</strong> [Número de Conmutador]</p>
                <p><i class="fas fa-envelope"></i> <a href="mailto:[correo de contacto general]">[correo de contacto
                        general]</a></p>
                <p><a href="{% url 'contacto' %}">Formulario de Contacto</a></p>
            </div>
        </div>
        <div class="copyright">
            <p>© 2025 Universidad Cooperativa de Colombia - Todos los derechos reservados.</p>
            <p><a href="{% url 'politicas' %}">Políticas de Privacidad</a> | <a href="#">Términos y Condiciones</a> | <a
                    href="#">Mapa del Sitio</a></p>
        </div>
    </footer>

</body>

</html>

task/templates/signup.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <title>Registro</title>
</head>

<body>
    <h1>Registrarse</h1>

    {% if form.non_field_errors %}
    <ul style="color: red;">
        {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}




    <form action="{% url 'signup' %}" method="POST">
        {% csrf_token %}

        <p>
            <label for="id_first_name">Nombre:</label>
            {{ form.first_name }}
            {% if form.first_name.errors %}
        <ul style="color: red;">
            {% for error in form.first_name.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        </p>

        <p>
            <label for="id_last_name">Apellidos:</label>
            {{ form.last_name }}
            {% if form.last_name.errors %}
        <ul style="color: red;">
            {% for error in form.last_name.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        </p>

        <p>
            <label for="id_email">Correo electrónico:</label>
            {{ form.email }}
            {% if form.email.errors %}
        <ul style="color: red;">
            {% for error in form.email.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        </p>

        <p>
            <label for="id_username">Nombre de usuario:</label>
            {{ form.username }}
            {% if form.username.errors %}
        <ul style="color: red;">
            {% for error in form.username.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        </p>

        <p>
            <label for="id_password1">Contraseña:</label>
            {{ form.password1 }}
            {% if form.password1.errors %}
        <ul style="color: red;">
            {% for error in form.password1.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        </p>

        <p>
            <label for="id_password2">Confirmar contraseña:</label>
            {{ form.password2 }}
            {% if form.password2.errors %}
        <ul style="color: red;">
            {% for error in form.password2.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        </p>

        <button type="submit">Registrarse</button>
    </form>
</body>

</html>